"""empty message

Revision ID: 91489264a74d
Revises: 
Create Date: 2019-10-06 01:00:13.864739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91489264a74d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('admin')
    )
    op.create_table('institute',
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('iname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('iid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institute')
    op.drop_table('admin')
    # ### end Alembic commands ###
