"""empty message

Revision ID: e73e006a68c9
Revises: 
Create Date: 2019-10-07 18:16:20.469725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73e006a68c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('admin', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('admin')
    )
    op.create_table('institute',
    sa.Column('iid', sa.Integer(), nullable=False),
    sa.Column('iname', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('iid')
    )
    op.create_table('paper',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('pname', sa.Text(), nullable=True),
    sa.Column('iid', sa.Integer(), nullable=True),
    sa.Column('passm', sa.Integer(), nullable=True),
    sa.Column('nm', sa.Integer(), nullable=True),
    sa.Column('awm', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_table('student',
    sa.Column('stid', sa.Integer(), nullable=False),
    sa.Column('sname', sa.Text(), nullable=True),
    sa.Column('iid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('stid')
    )
    op.create_table('questions',
    sa.Column('qid', sa.Integer(), nullable=False),
    sa.Column('iid', sa.Integer(), nullable=True),
    sa.Column('q', sa.Text(), nullable=True),
    sa.Column('a', sa.Text(), nullable=True),
    sa.Column('b', sa.Text(), nullable=True),
    sa.Column('c', sa.Text(), nullable=True),
    sa.Column('d', sa.Text(), nullable=True),
    sa.Column('ans', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['paper.pid'], ),
    sa.PrimaryKeyConstraint('qid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('student')
    op.drop_table('paper')
    op.drop_table('institute')
    op.drop_table('admin')
    # ### end Alembic commands ###
